name: Compile Interpreter

on:
  push:
    branches: [ senpai ]
  pull_request:
    branches: [ senpai ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile Interpreter
        run: php compile-utopia.php interpreter

      - name: Upload Interpreter
        uses: actions/upload-artifact@v2.2.2
        with:
          name: utopia-interpreter
          path: utopia-interpreter
          retention-days: 0

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Add clang to path
        shell: bash
        run: echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV

      - name: Compile Interpreter
        shell: bash
        run: php compile-utopia.php interpreter

      - name: Upload Interpreter
        uses: actions/upload-artifact@v2.2.2
        with:
          name: utopia-interpreter.exe
          path: utopia-interpreter.exe
          retention-days: 0
